app/blueprints/social/models.py
from datetime import datetime
from app import db, login
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin

@login.user_loader
def load_user(id):
    return User.query.get(int(id))

class User(UserMixin, db.Model):
    id= db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), unique=True, nullable=True)
    email = db.Column(db.String(120), unique=True, nullable=True)
    password_hash = db.Column(db.String(120), nullable=True)
    posts = db.relationship('Post', backref='author', lazy='dynamic')

    def __repr__(self):
        return f'<User: {self.username}>'
    
    def __str__(self):
        return f'User: {self.email}|{self.username}'
    
    def hash_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

    
    def commit(self):
        db.session.add(self)
        db.session.commit()

class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(140))
    body = db.Column(db.String(140))
    timestamp = db.Column(db.DateTime, default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

    def __repr__(self):
        return f'<Post {self.body}>'
    
    def commit(self):
        db.session.add(self)
        db.session.commit()

app/forms.py
from flask_wtf import FlaskForm 
from wtforms import StringField, PasswordField, SubmitField, TextAreaField, BooleanField
from wtforms.validators import DataRequired, EqualTo, Email

class RegisterForm(FlaskForm):
    username = StringField('Username', validators = [DataRequired()])
    email = StringField('email', validators = [DataRequired(), Email()])
    password = PasswordField('password', validators = [DataRequired()])
    confirm_password = PasswordField('confirm password', validators = [DataRequired(), EqualTo('password', message="Passwords must match!")])
    submit = SubmitField('Register')

class SignInForm(FlaskForm):
    username = StringField('Username', validators = [DataRequired()])
    password = PasswordField('Password', validators = [DataRequired()])
    remember_me = BooleanField('Remember Me')
    submit = SubmitField('Sign In')

class PostForm(FlaskForm):
    title = StringField('Title', validators = [DataRequired()])
    body = TextAreaField('Body', validators = [DataRequired()])
    submit = SubmitField('Submit Post')

app/__init__.py
from flask import Flask 
from config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate 
from flask_login import LoginManager
from flask_cors import CORS 


app = Flask(__name__)
CORS(app)
app.config.from_object(Config)
db = SQLAlchemy(app)
migrate = Migrate(app, db)
login = LoginManager(app)

login.login_view = '/sign_in'
login.login_message = "Make sure you log in"

from app.blueprints.auth import bp as auth_bp
app.register_blueprint(auth_bp)

from app.blueprints.main import bp as main_bp
app.register_blueprint(main_bp)

from app.blueprints.social import bp as social_bp
app.register_blueprint(social_bp)

from app.blueprints.api import bp as api_bp
app.register_blueprint(api_bp)

app/blueprints/api/__init__.py
from flask import Blueprint

bp = Blueprint('api', __name__, url_prefix='/api')

from . import routes

app/blueprints/api/routes.py
from . import bp as api_bp
from app.blueprints.social.models import Post,User


@api_bp.get('/posts')
def api_posts():
    result= []
    posts = Post.query.all()
    for post in posts:
        result.append({
            'id':post.id,
            'body':post.body,
            'timestamp':post.timestamp,
            'user_id':post.user_id
        })
    return result

@api_bp.route('/post/<id>', methods=['GET'])
def api_post(id):
    post = Post.query.get(int(id))
    return {
            'id':post.id,
            'body':post.body,
            'timestamp':post.timestamp,
            'user_id':post.user_id
        }

@api_bp.get('/user_posts/<username>')
def api_user_posts(username):
    result= []
    user = User.query.filter_by(username=username).first()
    for post in user.posts:
        result.append({
            'id':post.id,
            'body':post.body,
            'timestamp':post.timestamp,
            'user_id':post.user_id
        })
    return result

app/blueprints/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)



from . import routes

app/blueprints/main/routes.py
from . import bp as main_bp
from flask import render_template

@main_bp.route('/')
def index():
    cdn = {
        'instructors': ('lucas', 'dylan'),
        'students' : ['blane', 'ashmika', 'abe', 'zion', 'connor', 'martin', 'noah', 'erm']
    }
    return render_template('index.jinja', cdn=cdn, title='Home')

@main_bp.route('/about')
def about():
    return render_template('about.jinja')

app/blueprints/social/__init__.py
from flask import Blueprint

bp = Blueprint('social', __name__, url_prefix='/social')



from . import routes, models

app/blueprints/social/routes.py
from . import bp as social_bp
from .models import User, Post
from flask import redirect, render_template, flash, url_for
from app.forms import PostForm
from flask_login import login_required, current_user

@social_bp.route('/user/<username>')
def user(username):
    user_match = User.query.filter_by(username=username).first()
    if not user_match:
        redirect('/')
    posts = user_match.posts
    return render_template('user.jinja', user=user_match, posts=posts)

@social_bp.route('/post', methods = ['GET', 'POST'])
def post():
    form = PostForm()
    if form.validate_on_submit():
        body = form.body.data
        title = form.title.data
        p = Post(title=title, body=body, user_id= current_user.id)
        p.commit()
        return redirect(url_for('social.user', username = current_user.username))
    return render_template('post.jinja', post_form = form)

app/templates/about.jinja
{% extends "base.jinja" %}

{% block content %}
    <h2>About Page</h2>
{% endblock %}

app/templates/base.jinja
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% if title %}
    <title>{{ title }}</title>
    {% else %}
    <title>Welcome to FakeBook</title>
    {% endif %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</head>
<body class="container mt-1">
    {% include 'navbar.jinja' %}
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    <ul>
        {% for message in messages %}
            <li> {{ message }} </li>
        {% endfor %}
    </ul>
    {% endif %}
    {% endwith %}
    <h1>FakeBook CDN</h1>
    {% if current_user.is_active %}
        <p>Greetings {{ current_user.username }}</p>
    {% endif %}
    {% block content %}

    {% endblock %}
</body>
</html>

app/templates/index.jinja
{% extends "base.jinja" %}

{% block content %}
    <h2>CDN 109</h2>
    <h2>Instructors</h2>
    {% for instructor in cdn['instructors'] %}
        <span>{{ instructor }} </span>
    {% endfor %}
    <h2>Students</h2>
    {% for student in cdn.students %}
        <p>{{ student }}</p>
    {% endfor %}
{% endblock %}

app/templates/navbar.jinja
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="{{ url_for('main.index') }}">CDN FakeBook</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link active" aria-current="page" href="{{ url_for('main.index') }}">Home</a>
        <a class="nav-link" href="{{ url_for('main.about') }}">About</a>
        {% if current_user.is_active %}
        <a class="nav-link" href="{{ url_for('social.user', username=current_user.username)}}">Profile</a>
        <a class="nav-link" href="{{ url_for('social.post') }}">Post</a>
        <a class="nav-link" href="{{ url_for('auth.sign_out') }}">Sign Out</a>
        {% else %}
        <a class="nav-link" href="{{ url_for('auth.sign_in') }}">Sign In</a>
        <a class="nav-link" href="{{ url_for('auth.register') }}">Register</a>
       {% endif %}
        
      </div>
    </div>
  </div>
</nav>

app/templates/post.jinja
{% extends "base.jinja" %}

{% block content %}
    <h2>Post</h2>
    <form action="{{ url_for('social.post') }}" method="post">
        {{ post_form.hidden_tag() }}
        <p>
        {{ post_form.title.label }}<br>
        {{ post_form.title(size = 32) }}
        </p>
        <p>
        {{ post_form.body.label }}<br>
        {{ post_form.body(size = 32) }}
        </p>
        <p>
        {{ post_form.submit(class ='btn btn-primary') }}
        </p>
    
    </form>
{% endblock %}

app/templates/register.jinja
{% extends "base.jinja" %}

{% block content %}
    <h2>Register Page</h2>
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <p>
        {{ form.username.label }}<br>
        {{ form.username(size=32) }}
        {% for error in form.username.errors %}
        <span>{{ error }}</span>
        {% endfor %}
        </p>
        <p>
        {{ form.email.label }}<br>
        {{ form.email(size=32) }}
        {% for error in form.email.errors %}
        <span>{{ error }}</span>
        {% endfor %}
        </p>
        <p>
        {{ form.password.label }}<br>
        {{ form.password(size=32) }}
        {% for error in form.password.errors %}
        <span>{{ error }}</span>
        {% endfor %}
        </p>
        <p>
        {{ form.confirm_password.label }}<br>
        {{ form.confirm_password(size=32) }}
        {% for error in form.confirm_password.errors %}
        <span>{{ error }}</span>
        {% endfor %}
        </p>
        
        <p>{{ form.submit(class='btn btn-primary') }}</p>
    </form>
{% endblock %}

app/templates/sign_in.jinja
{% extends "base.jinja" %}

{% block content %}
    <h2>Sign-In Page</h2>
    <form action="" method="post">
        {{ sign_in_form.hidden_tag() }}
        <p>
        {{ sign_in_form.username.label }}<br>
        {{ sign_in_form.username(size = 32) }}
        </p>
        <p>
        {{ sign_in_form.password.label }}<br>
        {{ sign_in_form.password(size = 32) }}
        </p>
        <p>{{ sign_in_form.remember_me() }}  {{ sign_in_form.remember_me.label }}</p>
        <p>
        {{ sign_in_form.submit(class ='btn btn-primary') }}
        </p>
    
    </form>
{% endblock %}

app/templates/user.jinja
{% extends "base.jinja" %}

{% block content %}
<h2>{{ user.username }} Profile</h2>

{% for post in posts %}
    <p>{{ post.author.username }} says: {{ post.body }}</p>
{% endfor %}
{% endblock %}